FROM ubuntu:24.04

# # install curl
# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     curl && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN curl -LsSf https://astral.sh/uv/install.sh | less

RUN uv python install 3.12.9
