# https://hub.docker.com/_/postgres
# https://hub.docker.com/_/redis

services:
  postgres:
    # https://hub.docker.com/_/postgres
    image: postgres:17.5
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U $${POSTGRES_PASSWORD:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    # https://hub.docker.com/_/redis
    image: redis:7.4.2
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    command: redis-server --loglevel warning
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    volumes:
      - redis:/data

  server:
    image: ghcr.io/astral-sh/uv:python3.12-bookworm
    profiles:
      - server
      - debug
    ports:
      - 8000:8000
    user: ${MY_UID}:${MY_GID}
    environment:
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      VIRTUAL_ENV: ${PWD}/.docker/.venv
    volumes:
      - .:${PWD}
      - ${HOME}/.cache:/.cache
      - ./.docker/.venv:${PWD}/.venv
    working_dir: "${PWD}"
    command: uv run uvicorn server.main:app --reload
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  www:
    image: node:${MY_NODE}
    profiles:
      - client
      - debug
    # restart: unless-stopped
    environment:
      VITE_PROXY_URL: ${VITE_PROXY_URL:-host.docker.internal}
    volumes:
      - .:${PWD}
      - ${HOME}/.cache:/.cache
      - ${HOME}/.npm:/.npm
      - ${PWD}/.docker/node_modules:${PWD}/node_modules
    working_dir: "${PWD}"
    ports:
      - 5173:5173
    user: ${MY_UID}:${MY_GID}
    command: /bin/bash -c "npm install && npm run hdev"

volumes:
  postgres:
  redis:
