services:
  postgres:
    # https://hub.docker.com/_/postgres
    image: postgres:17.5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U $${POSTGRES_PASSWORD:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    # https://hub.docker.com/_/redis
    image: redis:7.4.2
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    command: redis-server --loglevel warning
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    # https://hub.docker.com/r/astral/uv
    image: ghcr.io/astral-sh/uv:python3.12-bookworm
    ports:
      - ${APP_PORT:-8000}:8000
    user: ${MY_UID}:${MY_GID}
    environment:
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      VIRTUAL_ENV: ${PWD}/.docker/.venv
    volumes:
      - .:${PWD}
      - ${HOME}/.cache:/.cache
      - ./.docker/.venv:${PWD}/.venv
    working_dir: "${PWD}"
    command: uv run uvicorn server.main:app --reload
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  www:
    # https://hub.docker.com/_/node
    image: node:${MY_NODE}
    restart: unless-stopped
    environment:
      VITE_PROXY_URL: ${VITE_PROXY_URL:-host.docker.internal}
      # APP_PORT and WWW_PORT are needed for Vite to configure HMR and proxy correctly
      # since the browser accesses these services externally to Docker
      APP_PORT: ${APP_PORT:-8000}
      WWW_PORT: ${WWW_PORT:-5173}
    volumes:
      - .:${PWD}
      - ${HOME}/.cache:/.cache
      - ${HOME}/.npm:/.npm
      - ${PWD}/.docker/node_modules:${PWD}/node_modules
    working_dir: "${PWD}"
    ports:
      - ${WWW_PORT:-5173}:${WWW_PORT:-5173}
    user: ${MY_UID}:${MY_GID}
    command: /bin/bash -c "npm install && npm run hdev"

  playwright-report:
    # https://hub.docker.com/_/node
    image: node:${MY_NODE}
    restart: unless-stopped
    volumes:
      - .:${PWD}
      - ${HOME}/.cache:/.cache
      - ${HOME}/.npm:/.npm
      - ${PWD}/.docker/node_modules:${PWD}/node_modules
    working_dir: "${PWD}"
    ports:
      - ${PLAYWRIGHT_REPORT_PORT:-9323}:9323
    user: ${MY_UID}:${MY_GID}
    command: npx playwright show-report --host 0.0.0.0 --port 9323

volumes:
  postgres:
  redis:
