"""create games table

Revision ID: ecef9cf8d452
Revises: 539823ed7cd0
Create Date: 2025-07-26 15:25:12.378148

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ecef9cf8d452"
down_revision: Union[str, Sequence[str], None] = "539823ed7cd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.Column("chat", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.execute(
        """
        CREATE TRIGGER set_updated_at
        BEFORE UPDATE ON games
        FOR EACH ROW
        EXECUTE PROCEDURE update_updated_at_column();
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    op.execute("DROP TRIGGER IF EXISTS set_updated_at ON games;")
    # ### end Alembic commands ###
